dir *.dayentry.xml | tidy-dasblog
dir *.dayentry.xml | tag-dasblog "PowerShell"
dir *.dayentry.xml | tag-dasblog "PowerShell" "Monad"
dir *.dayentry.xml | tag-dasblog "PowerShell" "MSH"
dir *.dayentry.xml | tag-dasblog "Zenzo"
dir *.dayentry.xml | tag-dasblog "ASP.NET"
dir *.dayentry.xml | tag-dasblog "Ruby"
dir *.dayentry.xml | tag-dasblog "Watir"
dir *.dayentry.xml | tag-dasblog "Ruby" "Watir"
dir *.dayentry.xml | tag-dasblog "DasBlog"
dir *.dayentry.xml | tag-dasblog "Javascript"
dir *.dayentry.xml | tag-dasblog "Internationalization"
dir *.dayentry.xml | tag-dasblog "Internationalization" "Globalization"
dir *.dayentry.xml | tag-dasblog "Internationalization" "Localization"
dir *.dayentry.xml | tag-dasblog "XmlSerializer"
dir *.dayentry.xml | tag-dasblog "Coding4Fun"
dir *.dayentry.xml | tag-dasblog "Diabetes" "Minimed"
dir *.dayentry.xml | tag-dasblog "Diabetes"
dir *.dayentry.xml | tag-dasblog "Diabetes" "GlucoPilot"
dir *.dayentry.xml | tag-dasblog "Diabetes" "Medtronic"
dir *.dayentry.xml | tag-dasblog "TechEd"
dir *.dayentry.xml | tag-dasblog "Speaking"
dir *.dayentry.xml | tag-dasblog "Speaking" "TechEd"
dir *.dayentry.xml | tag-dasblog "Speaking" "PDC"
dir *.dayentry.xml | tag-dasblog "PDC"
dir *.dayentry.xml | tag-dasblog "Subversion"
dir *.dayentry.xml | tag-dasblog "Subversion" "SVN"
dir *.dayentry.xml | tag-dasblog "NUnit"
dir *.dayentry.xml | tag-dasblog "NCover"
dir *.dayentry.xml | tag-dasblog "Nant"
dir *.dayentry.xml | tag-dasblog "XML"
dir *.dayentry.xml | tag-dasblog "CodeRush"
dir *.dayentry.xml | tag-dasblog "ViewState"
dir *.dayentry.xml | tag-dasblog "HttpHandler"
dir *.dayentry.xml | tag-dasblog "HttpModule"
dir *.dayentry.xml | tag-dasblog "Web Services" "SOAP"
dir *.dayentry.xml | tag-dasblog "Web Services"
dir *.dayentry.xml | tag-dasblog "NDoc"
dir *.dayentry.xml | tag-dasblog "Movies"
dir *.dayentry.xml | tag-dasblog "Movies" "Movie"
dir *.dayentry.xml | tag-dasblog "Gaming"
dir *.dayentry.xml | tag-dasblog "Gaming" "Game"
dir *.dayentry.xml | tag-dasblog "Gaming" "XBox"
dir *.dayentry.xml | tag-dasblog "Gaming" "PSP"
dir *.dayentry.xml | tag-dasblog "Africa"
dir *.dayentry.xml | tag-dasblog "Africa" "Zimbabwe"
dir *.dayentry.xml | tag-dasblog "Bugs" 
dir *.dayentry.xml | tag-dasblog "Bugs" "Bug" 
dir *.dayentry.xml | remove-category "Musings"
