//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("dasBlog 2.3.1")]
[assembly: AssemblyDescription("dasBlog 2.3.1 ASP.NET Blogging Engine")]
[assembly: AssemblyProduct("newtelligence dasBlog")]
[assembly: AssemblyCopyright("Copyright (c) 2012 newtelligence AG")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("22F15D36-4E7E-4c9b-A79C-F0A2177EE97B")]
[assembly: AssemblyVersion("2.3.12105.0")]
[assembly: AssemblyFileVersion("2.3.12105.0")]


